### ISSUE TITLE
Hyphenopoly does not work in shadow-root in chrome on windows

### ISSUE THREAD

**Issue by csvlad** [mnater/Hyphenopoly#130]
Hi!

I'm working with markdown text on my page. When I add markdown, it's being in #shadow-root (open). The system works perfectly on Mac OS with all hyphenations.

But, when I test it in Chrome and Edge on Windows 10 it doesn't work. It looks like the Hyphenopoly doesn't work in the shadow root with any lang. lang attribute is added.
![image](https://user-images.githubusercontent.com/52933579/84582405-3cafc880-adf4-11ea-9d83-9b37e9e01ba0.png)

Is there a way to solve this problem?

The part of code with Hyphenopoly styles and options I use in head:
```
<script>
var Hyphenopoly = {
    require: {
        "en-us": "FORCEHYPHENOPOLY",
        "ru": "FORCEHYPHENOPOLY"
    },
    setup: {
        CORScredentials: "omit",
        selectors: 
        { "#allrecords": {}
        // , ".markdown-body": {} // is included into #allrecords - the root tilda container
        }
    }
};
</script>
<script src="https://cdn.jsdelivr.net/gh/mnater/Hyphenopoly@4.5.0/Hyphenopoly_Loader.js"></script>

<script>
const addLangs = (selectorsToLangs = {'p': 'ru'}) => {
  for (let [selector, lang] of Object.entries(selectorsToLangs)) {
    const elements = document.querySelectorAll(selector);
    Array.prototype.slice.call(elements)
      .forEach(it => it.setAttribute('lang', lang));  
  }
}
</script>
<style type="text/css">
#allrecords {
    text-align: justify;
    hyphens: auto;
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
}
</style>
```

Many thanks!

**Comment by csvlad** [comment]
I've created a new HTML page that includes Shadow DOM. I've tested it on Mac OS and Windows 10.

 As you can see below, there 2 situations, when the system doesn't work on Windows (only English language works, when the text with other lang doesn't. (2nd screenshot))

Mac OS:

![photo_2020-06-14_19-25-17](https://user-images.githubusercontent.com/52933579/84598659-ff3f4f80-ae74-11ea-8d42-52b9b856c789.jpg)

Windows 10:
![Screenshot_1](https://user-images.githubusercontent.com/52933579/84598735-91dfee80-ae75-11ea-8b56-a65b411a2654.png)

The code of my page: https://gist.github.com/Vla2d/e7fdffced7fb973deb53b5d21c78e8a6

By the way, how can I fix the console errors?

**Comment by mnater** [comment]
Hi

Thanks for the report.
There are several issues here:

a) Hyphenopoly currently doesn't support hyphenation in ShadowDOM. Hyphenopoly uses `window.document.querySelectorAll` to find elements to hyphenate and `querySelectorAll` by design doesn't search in shadowDOM.
Supporting hyphenation of ShadowDOM-elements would be a nice feature, though.
While waiting for a fix you could use a [HTML-hyphenator](https://mnater.github.io/Hyphenopoly/Hyphenators.html#use-hyphenopolyhyphenatorshtml-for-dom-elements). In your example this could look like this:
````javascript
var template = document.querySelector("template");
var host = document.querySelector("#host");
var root = host.attachShadow({mode: 'open'});
root.appendChild(document.importNode(template.content, true));
Hyphenopoly.hyphenators.HTML.then((hyn) => {
    root.querySelectorAll("p").forEach((n) => {
        hyn(n);
    });
});
````

b) The english texts in your example already contain soft hyphens. That's why english is hyphenated.

c) You get these console warnings because Hyphenopoly is configured to hyphenate the element with id "#allrecords". But there's no such element in your example. Hyphenopoly warns about "unnecessarily" loaded languages.

Greetings,
Mathias
