### ISSUE TITLE
Webpack using hyphenopoly.module.js doesn't work

### ISSUE THREAD

**Issue by ghost** [mnater/Hyphenopoly#149]
This is the error I get when using hyphenopoly.module.js according to [docs](https://mnater.github.io/Hyphenopoly/Special-use-cases.html#webpack-hyphenopoly-module)

![image](https://user-images.githubusercontent.com/71846516/96833223-a448e500-1472-11eb-98a9-72d23c18cc1a.png)

The problem is that StringDecoder.write function does not accept Uint16Array objects in webpack.
Can you guys please check?

**Comment by mnater** [comment]
Since hyphenopoly.module.js is not really intended to be used with Webpack, I haven't tested it for a long time. Now with the current version of Webpack it seems to be even more complicated, because webpack > 5 does not contain polyfills for node.js core modules anymore.

Anyway, I can't manage to integrate hyphenopoly.module.js with webpack anymore.

Are you sure you want to do that? You get a much bigger package this way.
How did you configure webpack to get this far?

**Comment by ghost** [comment]
Here is my webpack config:
```
module.exports = {
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
};
```

**Comment by mnater** [comment]
What webpack version are we talking about?

**Comment by kaio-avila** [comment]
My webpack version is 4.44.1

**Comment by ghost** [comment]
My webpack version is 4.44.1

**Comment by mnater** [comment]
https://github.com/webpack/webpack/issues/11783

This does not seem to be an error in Hyphenopoly.
Is it ok if I don't pursue this any further, but invest the time to find out how to get Hyphenopoly running with a current webpack?

**Comment by ghost** [comment]
Yes, sure

**Comment by mnater** [comment]
Thanks.

https://github.com/mnater/Hyphenopoly/issues/150
