### ISSUE TITLE
hyphenopoly vs client hyphenation

### ISSUE THREAD

**Issue by nicolastaffin** [mnater/Hyphenopoly#174]
Hi,
i wonder is there is a way to PREVENT the client default hyphenation and prioritize hyphenopoly.
i'm very unhappy with french mac os monterey chrome hyphenation, and wonder if you implemented something
to take over it.

something like, for instance:

.hyphenate {
    -hyphenopoly-hyphens: auto; /* would trigger only hyphenopoly */
}

VS 

.hyphenate {
    hyphens: auto; /* would trigger the system hyphenation */
}

thanks

**Comment by mnater** [comment]
Hi

To always trigger hyphenopoly you can use the special keyword "FORCEHYPHENOPOLY" instead of a long word in the `require` field of your configs:

````javascript
Hyphenopoly.config({
    require: {
        "fr": "FORCEHYPHENOPOLY"
    }
});
````
https://mnater.github.io/Hyphenopoly/Global-Hyphenopoly-Object.html#require-mandatory

Also make sure to disable CSS client hyphenation.

Is this what you are looking for?

Kind regards,
Mathias

**Comment by nicolastaffin** [comment]
Thanks Mathias,

when you say :

> Also make sure to disable CSS client hyphenation.

Do you mean remove the hyphens: auto; CSS rule ?
I don't find another way to disable hyphenation in Chrome

**Comment by nicolastaffin** [comment]
Thanks.
