### ISSUE TITLE
Correction of hyphenation errors of certain words at system level? 

### ISSUE THREAD

**Issue by FrankConijn** [mnater/Hyphenopoly#20]
Is there a way to correct hyphenation errors of certain words at system level? If so, could you include a How To?

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenopoly/wiki/Setup#exceptions

**Comment by FrankConijn** [comment]
That leaves the entered words unhyphenated. I would like to correct the hyphenation, not remove it.

**Comment by mnater** [comment]
Hm, I can't reproduce this.
Could you provide some more details what you've done? – Or send me a link where I can see the issue?

**Comment by FrankConijn** [comment]
I think I misread the wiki section. First of all, 'exceptions' gave me the impression that the words entered in that function would not be hyphenated. I now see that they are, at the hyphen points. Is it correct that the hyphens in that function stand for soft hyphenation points, &amp;shy;s in the HTML?

**Comment by mnater** [comment]
'exceptions' is the word used in LaTeX for these kind of 'manually' (i.e. not by patterns) hyphenated words. So I thought this would be clear. Have you any suggestions for a better wording?

The words in the `exceptions`-list have to be divided by hyphen-minus (-). In HTML these words will be divided with soft hyphens (\&shy; by default) or whatever you set as a hyphen-character.

See http://mnater.github.io/Hyphenopoly/testsuite/test13.html for example (look at the source).

**Comment by mnater** [comment]
Added wiki-page about incorrect hyphenation: https://github.com/mnater/Hyphenopoly/wiki/Coping-with-hyphenation-errors

**Comment by FrankConijn** [comment]
I'd suggest to name that 'corrections'. People often do not read whole texts, but tend to go to the core of article or instruction directly. Further, FYI, I found that the words that your system hyphenates incorrectly are also done incorrectly by FF and Saf iOS. IE and Edge do them correctly. So, I put those words in spans and have a Javascript replace them with &amp;shy; versions, as in medewerkerstevredenheid ---> me&amp;shy;de&amp;shy;wer&amp;shy;kers&amp;shy;te&amp;shy;vre&amp;shy;den&amp;shy;heid. That covers all browsers and your system. It concerns a number of Dutch words.

**Comment by mnater** [comment]
> I'd suggest to name that 'corrections'.

I decided to stick with exceptions. Exception is more generic and it's too much work to change this.

> People often do not read whole texts, but tend to go to the core of article or instruction directly.

Well, that's definitely not my fault :-) But I try to give good examples…

> done incorrectly by FF and Saf iOS. IE and Edge do them correctly

Mozilla and Apple uses the same patterns as I do (https://github.com/hyphenation/tex-hyphen/blob/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-nl.tex). They haven't been updated since 1996. MS obviously has better patterns.

**Comment by FrankConijn** [comment]
1996? No wonder! 

FYI: 
1. I filed bug reports at the FF en Saf bug report sites. I'll let you know when they update their patterns, if they do.  
2. You might want to know, if you don't already, that IE did not ship with all available hyphenation dictionaries. Only with the English and system-language/s dictionary/ies, if available. I don't know about Edge, but the IE policy would be an argument to use your system even if all browsers natively support CSS hyphenation.

**Comment by mnater** [comment]
> I filed bug reports at the FF en Saf bug report sites. I'll let you know when they update their patterns, if they do.

Since FF and Apple rely on TeX patterns it would be better to file bugs to http://www.hyphenation.org/tex#introduction or even become the maintainer of the nl-patterns…

> You might want to know, if you don't already, that IE did not ship with all available hyphenation dictionaries. [...] the IE policy would be an argument to use your system even if all browsers natively support CSS hyphenation.

I think FF is the only browser that supports almost all languages available for TeX. The other browsers only support a subset (sometimes depending on the installed directories, as you noted). This is mostly due to licencing concerns and lack of user request but may also be caused by the poor quality of some patterns. This is where Hyphenopoly fills the gap.

**Comment by FrankConijn** [comment]
I might just as well become the maintainer of the NL pattern. I sent an email to the listed maintainer some 10 days ago, but still no response. And if 1996 is the year of the last update, the man might not be able anymore.
