### ISSUE TITLE
JS Interface Documentation

### ISSUE THREAD

**Issue by jdichev** [mnater/Hyphenopoly#26]
Hello,

I would like to use Hyphenopoly in a single-page application via a JS interface. I would image that should look something like the Node.js usage example but cannot find any docs on the topic.

Could you please help - where should I look?

Thanks and best regards,
Jordan

**Comment by mnater** [comment]
Hi

There are no docs for this use case. I've never thought of it.
Could you please elaborate what you're planning to do and what you've tried so far?

Best regards,
Mathias

**Comment by jdichev** [comment]
Hi,

My use case is basically programmatic API for the browser. I give string input to Hyphenopoly and get hyphenated string as output.

Also adding a few details:

* Hyphenopoly dependency can be loaded and active at run time
* The dependency provides an async API similar to the Node.js example in the main docs
* If possible, a synchronous API alternative would be really useful

What I tried so far was to load Hyphenopoly via the loader script and play with the API.

Also currently trying to export a browser-friendly script of the node module using Browserify but need more time there as it looks like it won't work out of the box.

Best regards,
Jordan

**Comment by mnater** [comment]
Hi

Thanks for clarification.

The node-module requires "fs" and "util". These would probably need to be replaced by a browserified package.

Currrently you can access the `hyphenateFunction` when the engine is ready:
````html
        <script>
        const Hyphenopoly = {
            require: {
                "en-us": "FORCEHYPHENOPOLY"
            },
            handleEvent: {
                engineReady: function (e) {
                    if (e.msg === "en-us") {
                        console.log(Hyphenopoly.languages["en-us"].hyphenateFunction("hyphenation", "•", 2, 2));
                        //logs: hy•phen•ation
                    }
                }
            }
        };
        </script>
        <script src="../Hyphenopoly_Loader.js"></script>
````
The hyphenateFunction is language specific and takes 4 arguments:

1.  \<string> The word to hyphenate
2. \<string> The hyphen character
3. [\<number>] The optional leftmin value
4. [\<number>] The optional rightmin value

And returns the hyphenated word.

The `engineReady` event fires asynchronously when the patterns are loaded and the (w)asm engine is instantiated.

That's not very user friendly and not documented. I'll try to find a better solution.

The idea: return a Promise for the `hyphenateFunction`

About __synchronous API alternative__:
I don't think that's possible since loading the ressources and instantiating the wasm-engine are both async.

**Comment by jdichev** [comment]
Hi Mathias,

Thank you for the help. That was exactly what I was looking for. Tried it and it worked nicely.

Indeed your example above is also is the combination of async and sync APIs I hoped for and it should cover the sync case I mentioned.

My main need is that the ```hyphenateFunction``` has at least a sync version. It is perfectly OK to wait until all prerequisites are loaded.

Best regards,
Jordan
