### ISSUE TITLE
Use node version with browser.

### ISSUE THREAD

**Issue by denbezrukov** [mnater/Hyphenopoly#35]
Hi, thank you for tool!!
How can I use a node version with a browser?
Instead of trigger the 'contentLoaded', I want to call the library like node on client side.
Is it possible?

**Comment by mnater** [comment]
Hi

Honestly, I haven't thought of that. I don't know if this is currently possible…
I'll need some more information:

1. What have you tried so far? Have you tried something like [browserify](http://browserify.org)?
2. What's your use case?

**Comment by denbezrukov** [comment]
Thx for answer! 
I’m using react+redux with bundle module by the webpack. I want after fetch some data from a server make some field hyphenated and save it in a store. If I trigger ‘contentLoaded’ after a mutation (insert or change text in subtree) main node, screen makes “flash” every time.
And I can’t do it in server side :(
Sorry for my english (: 

UPD: May be make a static method of Hyphenopoly which return Promise/Async like the node version? 
UPD2: Something like [Hyphenator method](https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#mixed-hyphenatorhyphenatemixed-target-string-lang)

**Comment by mnater** [comment]
Yep
Now, I perfectly understood what you need.

Implementing will take some time, please be patient.
I'll document the progress here.

**Comment by denbezrukov** [comment]
Cool!
I suppose that someone will use it in a universal app. What do you think about it?

**Comment by mnater** [comment]
~~Work is ongoing in separate branch: https://github.com/mnater/Hyphenopoly/tree/expose~~

merged: https://github.com/mnater/Hyphenopoly/commit/f30df8fea05af4c452b4faecd828db7d676025e1

documentation: https://github.com/mnater/Hyphenopoly/wiki/Hyphenators

**Comment by mnater** [comment]
Does this work for your use case?

PS:
With some small changes (explained here: https://github.com/mnater/Hyphenopoly/wiki/browserify) `hyphenopoly.module.js` is now (https://github.com/mnater/Hyphenopoly/commit/349fd6109403af8986b7ea78b7ce8e23d785ecfa) compatible to browserify.

This may be another approach.

**Comment by denbezrukov** [comment]
Yep, you save my day!

What do you think about a "universal" version? 
I mean about the same interface of using API. 
For example: 
I require and setup Hyphenopoly as a global instance on a node side.
On a client side, if need polyfil, dynamically load by Webpack and setup as a window instance.

I will try to make a universal react component which will polyfill hyphens auto css property.

**Comment by mnater** [comment]
> Yep, you save my day!

😄 

> What do you think about a "universal" version?

Both sides of "universal" are already available: use `Hyphenopoly_Loader.js` and `Hyphenopoly.js` on client side and use `hyphenopoly.module.js` on server side.

Having an "universal" version (in my understanding a common codebase, that "compiles" to a browser version or to a node version) would indeed save some dublicate code. I've tried but wasn't happy with the results (code size and performance). So I gave up on this.

I thought I'd cover all the use cases with these two 'packages'. But since you came up with react (which I don't know very well) maybe server side rendering (SSR) may be a new use case?
How would that work?

Idea:
1. Run feature test to see if client supports css-hyphens
2. Client requests a component and tells if it needs to be hyphenated
3. Server serves the corresponding component (pre-hyphenated or not)
4. Client adds the component to the DOM

This could work, but I personally don't like the design. I think hyphenation is part of the layout-process and that belongs to the client (the fact that `hyphens` is in CSS supports that).

So I'd prefer the following:
1. Run feature test to see if client supports css-hyphens
2. Client requests a component
3. Server serves the corresponding component
4. Client hyphenates the component (if necessary) and then adds it to the DOM.

But maybe you can convince me otherwise?
