### ISSUE TITLE
WebAssembly.Memory() error when requiring many languages in Node

### ISSUE THREAD

**Issue by lehni** [mnater/Hyphenopoly#38]
I've added 29 languages to the `require` statement, and now I'm getting the error below when running the program:

```js
const hyphenator = hyphenopoly.config({
  require: Object.keys(hyphenationLanguages)
})
```

```
/.../node_modules/hyphenopoly/hyphenopoly.module.js:380
    const wasmMemory = new WebAssembly.Memory({
                       ^
RangeError: WebAssembly.Memory(): Property value 256 is below the lower bound 196
    at instantiateWasmEngine (/.../node_modules/hyphenopoly/hyphenopoly.module.js:380:24)
```

**Comment by lehni** [comment]
This is the `hyphenationLanguages` list currently:

```js
export const hyphenationLanguages = {
  af: 'Afrikaans',
  as: 'Assamese',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bg: 'Bengali',
  ca: 'Catalan / Valencian',
  cs: 'Czech',
  cu: 'Church Slavonic',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  'el-monoton': 'Modern Monotonic (single accent) Greek',
  'el-polyton': 'Modern Polytonic (multi accent) Greek',
  'en-gb': 'English (UK)',
  'en-us': 'English (US)',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fi: 'Finnish',
  fr: 'French',
  fur: 'Friulan',
  ga: 'Irish',
  gl: 'Galician',
  grc: 'Ancient Greek',
  gu: 'Gujarati',
  hi: 'Hindi',
  hr: 'Hausa',
  hsb: 'Upper Sorbian',
  hu: 'Hungarian'
}
```

**Comment by mnater** [comment]
Hi

Thanks for the report.
 If I delete the line for 'Church Slavonic' it works well here. Looks like this is rather a problem with the `cu` patterns than with the number of languages...

**Comment by lehni** [comment]
oh interesting! I was just starting to compile a file that maps the available languages to their actual names. Should this be maybe added to the library, it could be of use? I don't actually need `cu` : )

**Comment by mnater** [comment]
Some notes about the bug:

Church Slavonic patterns have a large set of characters (120 pairs of lower-/uppercase chars and some diacritics). The size of the pattern trie thus gets very big (over 20MB!). That exceeds the current upper limit I set for wasm-memory (16MB).
The RangeError disappears if we raise the limit and recompile the wasm-module.
Nevertheless hyphenation doesn't seem to work for Church Slavonic. Looks like there are issues with diacritic marks.
Since Church Slavonic is a corner case I'm not going to spend more time on this and drop `cu.hpb` from the list until someone really requires its support (and helps implementing it)…

About mapping from language-codes to language-names:

I'm not sure if I understand correctly. Are you proposing a mapping that would allow something like the following?
````javascript
const hyphenator = hyphenopoly.config({
  require: ["German", "English (US)"]
})
````
Then I'd rather stick with the language-codes. They are well defined and universally accepted.

Best regards,
Mathias

PS: Grüess us Züri

**Comment by lehni** [comment]
Yes that sounds reasonable!

Regarding the language mapping: I thought it could be useful to have some kind of mapping from the language code to something a bit more readable, just for human readability. Instead of mapping them to english terms, it may be more useful if it was mapped to some common language / region standard, which then could be further mapped to any translation through some other library? Or what are the current language codes exactly? It doesn't seem to be quite a standard?

Something along these lines:

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

See `[language designator]-[region designator] `

PS: Grüezi zrugg! Bin au in Züri!

**Comment by lehni** [comment]
PS: Grüezi zrugg! Bin au in Züri!

**Comment by mnater** [comment]
Language tags are defined in different ISO standards. See https://tools.ietf.org/html/bcp47 for an overview.
I try to follow these rules.

**Comment by lehni** [comment]
ok great! I'll take a look, thank you

**Comment by lehni** [comment]
Shall we close this since you already addressed the issue in 39a32389f5414abfa88feab22583462628e6141c?

**Comment by mnater** [comment]
Yep

**Comment by lehni** [comment]
I still have a question regarding the language standard... wouldn't it make sense to just use one standard that matches all languages, or al least support multiple standards fully and convert between them internally? It seems like `ISO 639-3` with its three letter code would match languages more precisely? See https://iso639-3.sil.org/about/types, https://iso639-3.sil.org/about/relationships

>  ISO 639-3 was devised to provide a comprehensive set of identifiers for all languages for use in a wide range of applications, including linguistics, lexicography and internationalization of information systems. It attempts to represent all known full languages.

**Comment by mnater** [comment]
Allthough there are different `ISO 639-x` standard files they together form one `ISO 639` standard (consisting of different parts 1-5).
The language defined in `ISO 639-1` (the two-letter language codes) are a subset of `ISO 639-2` (three-letter codes) are a subset of `ISO 639-3`, but not vice versa and the whole standards are not subset of each others. So we can't necessarily convert between them in all cases.
[BCP47#2.2.1](https://tools.ietf.org/html/bcp47#section-2.2.1) tells us to give precedence to two-letter codes over three-letter codes if both are defined.

I think we should stick with this practice here since almost everybody in the Internet follows IANA's bcp47. This small project isn't the right place to start a revolution ;)

**Comment by lehni** [comment]
Sounds right! You can probably tell, I'm new to all these standards :)
