### ISSUE TITLE
Double hyphen in Firefox

### ISSUE THREAD

**Issue by BeckyDTP** [mnater/Hyphenopoly#43]
Windows 10 Pro x64 Polish
Firefox 63.0.1 x64 Polish
Hyphenopoly (newest)

In Firefox Hyphenopoly adds hyphen in words _x-abcdefg_… (for example: **e-commerce**, **e-bookami**, **n-kreślny**, **A-klasowy**, **L-karnityna**, **T-Mobile**, **u-kształtny**, **X-Factor**)

![doublehyphenfirefox](https://user-images.githubusercontent.com/22416021/48545642-aee1c380-e8c6-11e8-8e4a-18c4a0d61b2f.png)

These are normal words in Polish (although the problem is not only about the Polish language).

If the problem is Firefox then maybe some workaround?

**Comment by mnater** [comment]
Hi

Please post the source of your changed example1.html file.

**Comment by BeckyDTP** [comment]
Changed (added _e-commerce_ word to English text to highlight the problem).
[example-issue.html.zip](https://github.com/mnater/Hyphenopoly/files/2585163/example-issue.html.zip)

**Comment by mnater** [comment]
Thanks

I was able to reproduce the issue (only in Firefox, but on Mac, too).

In this case Hyphenopoly does nothing, because FF does support native hyphenation for `pl` and `en`. It's a bug in Firefox. We should file it on https://bugzilla.mozilla.org

I don't know a workaround except enforcing the usage of Hyphenopoly (see https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#require and https://github.com/mnater/Hyphenopoly/wiki/Setup#compound).

Best regards,
Mathias

**Comment by mnater** [comment]
Other idea for a workaround—although not very practical:

Use a non-breaking hyphen `&#8209;` instead of a hyphen:
`e&#8209;commerce`
This inhibits the linebreak.

And if you insert a zero width space (`&#8203;`) after the non-breaking hyphen it may break without an additional hyphen.

**Comment by BeckyDTP** [comment]
Thank you. As a temporary solution should be useful.

Unfortunately, I suspect my English is not good enough to explain the problem to Firefox developers.

**Comment by mnater** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1507661
