### ISSUE TITLE
Wordpress de-DE

### ISSUE THREAD

**Issue by MichaelEnkirch** [mnater/Hyphenopoly#44]
Hi,
inside a Wordpress Theme im using this <?php language_attributes(); ?> to get the language. For german i get "de-DE". 

So if i add
"de-DE": "Silbentrennungsalgorithmus" as required, the pattern file "de-DE.hpb" is 404.

Now i copy the pattern file de.hpb and rename it to "de-DE.hpb"

But nothing happens. No Error Message in the console. 

Is there anyway i can fix this, without geting rid of the wordpress function and write lang="de" by myself?

**Comment by mnater** [comment]
Hi

Thanks for the report. That‘s an issue with case sensitiveness. (Also see #41)
I hope to be able to work on this the next days.

**Comment by enky00** [comment]
Mhh still not working for me with with lng="de-DE" in the html tag.

Getting in Chrome
Element with 'de-de' found, but 'de-de.hpb' not loaded. Check language tags!

Still have to rewrite it to lng="de". 

Not the best solution, because other plugins could liste too exactly "lng='de-DE'".


And if use the new loader.js, my wordpress page (localhost, sry no link), stays empty. i tried to figure out why, but there are no error logs. the html looks good, but the screen is white.


So i just try and error trough the new loader.js. and found this.

if i delete line 654 (H.toggle("off");) its inside the function run. it works in chrome , and the "shy" tags are appearing.

**Comment by enky00** [comment]
Mhh still not working for me with with lng="de-DE" in the html tag.

Getting in Chrome
Element with 'de-de' found, but 'de-de.hpb' not loaded. Check language tags!

Still have to rewrite it to lng="de".

Not the best solution, because other plugins could liste too exactly "lng='de-DE'".

And if use the new loader.js, my wordpress page (localhost, sry no link), stays empty. i tried to figure out why, but there are no error logs. the html looks good, but the screen is white.

So i just try and error trough the new loader.js. and found this.

if i delete line 654 (H.toggle("off");) its inside the function run. it works in chrome , and the "shy" tags are appearing.

**Comment by mnater** [comment]
Hmm. Works here.

Could you please post the code of your page so I can track down the issue or send it by e-mail (mathiasnater@gmail.com)

**Comment by enky00** [comment]
````php
function hyphenopoly_loader(){
    ?>
    <script>      
            if(window.self === window.top) {
                var Hyphenopoly = {
                    require: {
                       "de": "Silbentrennungsalgorithmus"
                    },
                    paths: {
                        patterndir: "<?php echo get_stylesheet_directory_uri(); ?>/js/hyp/patterns/",
                        maindir: "<?php echo get_stylesheet_directory_uri(); ?>/js/hyp/"
                    },
                    setup: {
                        classnames: {
                            "Hyphenopoly": {},
                        }
                    }
                };      
            }
    </script>
    <script src="<?php echo get_stylesheet_directory_uri(); ?>/js/hyp/Hyphenopoly_Loader.js"></script>
    <?php
}
add_action('wp_head', 'hyphenopoly_loader');
````


This is the way i include it. the code is in the functions.php of my theme. There isnt much more there.

**Comment by mnater** [comment]
You must define a fallback:

````javascript
var Hyphenopoly = {
    require: {
        "de-de": "Silbentrennungsalgorithmus"
    },
    fallbacks: {
        "de-de": "de"
    },
    paths: {...},
    setup: {...}
};
````

[See (updated) description](https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#require)
