### ISSUE TITLE
settings for `minWordLength`, `leftmin` and `rightmin` in all Browsers

### ISSUE THREAD

**Issue by astridx** [mnater/Hyphenopoly#55]
Many thanks for this extension. I hope I may ask something again.
I'm using `hyphenopoly` and hyphenation only recently. 

In Firefox my settings for `minWordLength`, `leftmin` and `rightmin` are ignored. Here are the CSS setting used - I think. 
Chrome used my settings for the options `minWordLength`, `leftmin` and `rightmin`. 

Is there a way to use the options in all browsers?

**Comment by mnater** [comment]
Please post your code or send a link to the website where I can see the issue.

**Comment by astridx** [comment]
Thank you very much for the quick reply.
I just installed everything online in a test system: https://awo.astrid-guenther.de/

In Firebox on Ubuntu 18.04 I see `leftmin` of 2 characters. For example Da-men
In Chrome everything is fine.
I emptied Browser Cache and I see no errors in Web Console. 

![home 1](https://user-images.githubusercontent.com/9974686/51668638-f40b2b80-1fc2-11e9-930b-ce6f7a702e96.png)

**Comment by astridx** [comment]
Sorry. I closed the issue by mistake

**Comment by mnater** [comment]
Hi

That is expected behaviour.
You require two languages: de-de and en-gb. Both languages are supported by native CSS-hyphenation in Firefox. So hyphenation is done by the browser and the settings for Hyphenopoly.js are not taken in account.
Chrome (on Windows - I haven't tested it on Ubuntu) doesn't support hyphenation (yet). Hyphenopoly.js gets loaded and your settings are used.

If you always want to use Hyphenopoly.js [enforce Hyphenopoly](https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#require).
