### ISSUE TITLE
Webpack compatibility ?

### ISSUE THREAD

**Issue by AKKlostermann** [mnater/Hyphenopoly#70]
I looked over the issues and the docs and I believe this has not yet been asked.

I'm trying to import it inside a Webpack project. Webpack uses ES modules (import). When I do that however, it complains about "fs" module not being found, apparently trying to run/import the node version.

Mainly I need this for use inside React components, because Chrome should do hyphenation but in practice it doesn't. I probably could serve and load the hyphenator file separately, but I would prefer staying inside the typescript/react/webpack tooling if possible...

Has this been considered before? Thank your for the time you invest in this project and answering the issues!

**Comment by mnater** [comment]
Hi

Thanks for the question.

I'm not very well versed in webpack, but I'll have a look…

I've only tested with `browserify` so far: [browserify-hyphenopolymodulejs](https://github.com/mnater/Hyphenopoly/wiki/Special-use-cases#browserify-hyphenopolymodulejs). May be that could help?

Regards,
Mathias

**Comment by AKKlostermann** [comment]
I think the problem is this: https://github.com/mnater/Hyphenopoly/blob/master/hyphenopoly.module.js#L17

Webpack probably tries to find "fs" and fails, rather than return undefined.

**Comment by mnater** [comment]
Yep, that's correct.

We should define the loader ("fs" in node-environment and "http" in browser-environment) in `H.config`.

This will need some time and testing (and I'll have to wrap my head around webpack).

**Comment by mnater** [comment]
Until then: as a workaround just replacing "fs" with "http" in line https://github.com/mnater/Hyphenopoly/blob/master/hyphenopoly.module.js#L17 should do the trick

**Comment by mnater** [comment]
Hi

I think I found the solution.

__tldr;__
Tell webpack to shim the `fs`-module with an `"empty"` object.

Webpack.config.js:
````javascript
module.exports = {
  node: {
    fs: "empty"
  }
};
````

With this everything works with the current implementation (Version 3.0.1)

----
__My full setup__

mkdir h9ywp
cd h9ywp/
npm init -y
npm install webpack --save-dev
npm install webpack-cli --save-dev
npm install hyphenopoly
mkdir src
cd src/
touch index.js

````javascript
"use strict";

const hyphenopoly = require("hyphenopoly");

const hyphenator = hyphenopoly.config({
    "require": ["de", "en-us"],
    "paths": {
        "maindir": "../node_modules/hyphenopoly/",
        "patterndir": "../node_modules/hyphenopoly/patterns/"
    },
    "hyphen": "•",
    "loader": "http"
});

async function addDiv(lang, text) {
    const hyphenateText = await hyphenator.get(lang);
    const element = document.createElement('div');
    element.innerHTML = hyphenateText(text);
    document.body.appendChild(element);
}

(async function () {
    await addDiv("de", "Silbentrennung verbessert den Blocksatz.");
    await addDiv("en-us", "hyphenation enhances justification.");
})();
````

cd ../
mkdir dist
cd dist/
touch index.html

````html
<!doctype html>
  <html>
    <head>
      <title>Hyphenopoly webpack test</title>
    </head>
    <body>
      <script src="main.js"></script>
    </body>
  </html>
````

cd ../
package.json:
````json
{
  "name": "h9ywp",
  "version": "1.0.0",
  "description": "Test hyphenopoly with webpack",
  "private": "true",
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.0"
  },
  "dependencies": {
    "hyphenopoly": "^3.0.1"
  }
}
````

touch webpack.config.js

_important_: tell webpack to shim the `fs`-module with an `"empty"` object.
````javascript
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  node: {
    fs: "empty" //<- prevent "fs not found"
  }
};
````

npx webpack --config webpack.config.js

**Comment by mnater** [comment]
~~wiki updated: https://github.com/mnater/Hyphenopoly/wiki/Special-use-cases#webpack~~

doc: https://github.com/mnater/Hyphenopoly/blob/master/docs/Special-use-cases.md#webpack

**Comment by AKKlostermann** [comment]
This doesn't really work for me. I've had to add a file-loader for the hpb files, require them, and now I'm trying to work out how to make the wasm load.

There may be an easier way to structure the library for use in webpack, parcel and the like. I'm not yet good enough with that technology to see it.

**Comment by mnater** [comment]
Yes, there are other ways. Packages like [hyphen](https://www.npmjs.com/package/hyphen) work that way. They require the patterns to be preloaded.

Hyphenopoly on the other hand tries to dynamically load patterns based on user configuration. This has the advantage that in an app with multiple languages only the languages required by the user have to be loaded.

The node module of Hyphenopoly (`hyphenopoly.module.js`) isn't really intended to work in a browsers environment. IMHO it's not good to load the module and the patterns in all browsers regardless of their native hyphenation support.

That's why I recommend to use `Hyphenopoly_Loader.js`. This checks if the browsers really needs Hyphenopoly and if so loads the Hyphenopoly script, the wasm (or asm) and the required patterns. So users of browsers that support native hyphenation (for most languages thats all browsers but Chrome on Windows) will not have to load the whole package…

Now, I don't know your use case. If it's just about polyfilling native CSS hyphenation for Chrome (on Win) I'd recommend to directly load `Hyphenopoly_Loader.js` from your index.html and use [Hyphenators](https://github.com/mnater/Hyphenopoly/wiki/Hyphenators) to hyphenate dynamically added elements.

**Comment by ahwitz** [comment]
FYI: I'm fairly certain that after https://github.com/mnater/Hyphenopoly/commit/2b3da7deb20b440871549adcccf9bfe493574b71, the recommended Webpack solution now spits out a `Critical dependency: the request of a dependency is an expression` warning every time compilation happens, because of the variable being passed in to `require`.

**Comment by mnater** [comment]
Thank you for this precise report. I'll look into it.

**Comment by mnater** [comment]
Fixed in https://github.com/mnater/Hyphenopoly/commit/5f7c7e5de7aeda5352727000b3e884d17566bbd9

But not ready to land (waiting for cdnjs to merge https://github.com/cdnjs/cdnjs/pull/13323 to be able to check http loading)

**Comment by ahwitz** [comment]
Not a problem for us; due to the same issue as AKKlostermann above, Hyphenopoly can't easily do what we need, so we've decided on using a different library. Just wanted to pass on the bug report after I bandaid-ed it while poking around. Thanks for getting to it so fast regardless!

**Comment by urbgimtam** [comment]
I'm trying to use Hyphenopoly with NuxtJs and also got stuck on this problem.
As it uses SSR, the use case described for React doesn't also work for me.
Any chance this bug could be fixed in the future?
