### ISSUE TITLE
Javascript soft hyphens the only option for browsers?

### ISSUE THREAD

**Issue by FrankConijn** [mnater/Hyphenopoly#80]
There are reports that the Google bot has started executing Javascript, except certain scripts/under certain circumstances. That means that it would read 'tech&amp;shy;nique' in stead of 'technique'. Which has implications for the SEO. 

Is Javascript the only option in Hyphenopoly for browsers? 

PS: Your script has gained value, since Microsoft decided to switch to Chromium as the engine for Edge. (Chrome still does not support CSS hyphenation on Windows, and only for English on Android 6+, for those who don't know.)

**Comment by ReLater** [comment]
Just as a suggestion: I have a "Don't load Hyphenopoly if bot" managed by PHP. In a Joomla-Plugin where it's easy to identify bots with a 1-liner. But I know that's not always that easy in other systems.

**Comment by mnater** [comment]
To my knowledge google has no issues with indexing words that contain soft hyphens. Do you now more?

Chrome on Windows does not support hyphenation because MS did not give access to the hyphenation API (see [this Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=605840#c31)). This may change when Edge
uses Chrome... The usecase for Hyphenopoly will then be marginalized to unsupported (rare) languages.

**Comment by FrankConijn** [comment]
Well, *knowing* how the Google bot works is quite difficult, because Google is very secretive about that. As you will know. But I'm gonna have some really angry clients if it appears that the Javascript-inserted soft hyphens do interfere with the indexation. So I have to be sure that it doesn't. 

I can make it so that Hyphenopoly is not executed if the client is a Google or Bing bot, but maybe you had a simpler solution. 

Furthermore, thanks for your honest answer on the issue of Chrome on Windows support for hyphens:auto, and what that means for the future. Which on the other hand makes me wonder: why did you make your system so much more bloated and complicated than Hyphenator? I'd think that the easier and smaller the system, the greater the chance that web designers in other languages than English will use it?

**Comment by mnater** [comment]
> Well, knowing how the Google bot works is quite difficult …  So I have to be sure that it doesn't.

We can never be sure about that.

We could make a test: create a page with a fantasy word that gets hyphenated and see how the Google Web Crawler handles it. Then we would know for now. But we never now what happens tomorrow. Maybe some engineer decides to change how soft hyphens are treated by the bot and our findings are worthless.

> why did you make your system so much more bloated and complicated than Hyphenator?

Is it bloated?

The Hyphenopoly_Loader is larger than Hyphenator_Loader. That's true. The other ressources are smaller (at least when minified and compressed).
Hyphenopoly_Loader is larger because it does a lot more: feature test for wasm, start download of ressources earlier in the whole process which gives higher responsivness (with Hyphenator patterns were downloaded when the main script has been executed) and to handle all kind of errors that could occur, it needs a basic event handling.

Is it complicated?

There's always a tradeoff.
I wanted to have the patterns as small as possible (for many languages they are the haviest part). So I needed a fast engine that handles the binary, creates the pattern trie and hyphenates words. That's the asm.js/wasm part. Running asm/wasm is complicated but as this technology (wasm) evolves there will be easier ways – I hope.

Hyphenopoly still supports IE11. I could drop support for IE11 and rely on `fetch`, `wasm` and `promises` being supported. Then I could drop lots of polyfilling code (asm.js, xmlHTTPRequest), use promises instead of the event system) and inline wasm in Hyphenopoly.js.

Maybe I should drop support for IE11 in version 4 and only fix bugs in version 3…

**Comment by FrankConijn** [comment]
> Maybe I should drop support for IE11 in version 4 and only fix bugs in version 3…

I'd say that's a very good idea, because of two reasons. The first is that, as you will know, Microsoft is ending support for Win7 end of this year, and the upgrade to Win10 is cheap, if not free. So most people will upgrade, and thus start using Edge. 

The second reason is that in my experience, IE 10+ has excellent CSS hyphenation, in all system languages available. In Dutch, it's even better than the hyphenation by FF or Hyphenopoly (due to the poorly maintained Dutch pattern that the latter have to use). 

Any idea when you're going to release version 4?

**Comment by andremacola** [comment]
> Maybe I should drop support for IE11 in version 4 and only fix bugs in version 3…

That would be awesome. Here we have an internal system to generate pdf's with no support for IE and will love a smaller version and modern browser only.

**Comment by mnater** [comment]
This is going to be a greater step, but I'm making good progress.
There will be a smaller release in the next days (end of June) that prepares for this major change (I transferred the documenation from the wiki to a docs/ folder – so the documentation can be version specific).
I'm planning to go public with a "modern browser only"-version by the end of August.

**Comment by mnater** [comment]
"It took a while"...
Major update is coming: https://github.com/mnater/Hyphenopoly/commit/c67af7ac2158ac56ae178567b1591783bab9a055

**Comment by FrankConijn** [comment]
That would be nice! Looking forward to it.

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenopoly/releases/tag/v4.0.0
