### ISSUE TITLE
Unable to focus element when Hyphenopoly is active

### ISSUE THREAD

**Issue by Bertijn** [mnater/Hyphenopoly#89]
On my project, I encountered another problem, but I didn't have the time to debug it this time.

We are focusing certain elements on certain pages, such as inputfields for searchpages, on the page init. However, on Windows Chrome, where Hyphenopoly is used, the input doesn't get focused. 

Sometimes, we get a Hyphenopoly timeout message, Hyphenopolys 'FOUHC'-prevention timed out after ... ms, after which the focus worked. Tested on Browserstack.

I currently fixed the problem by putting a timeout of 500ms around the focus code, but now we noticed that was not the only place we use to focus something on init, so we had to fix it there as well.

Kind regards,
Bertijn

**Comment by mnater** [comment]
Hi

Thanks for reporting. I‘d like to reproduce this issue. Could you please post the code or a link, where I can see what you are doing?

Thanks

**Comment by mnater** [comment]
I think I found the source of the problem: `HTMLElement.focus()` doesn't work if the element is hidden (that makes sense since setting the focus on a invisible element would have no effect).

By default Hyphenopoly_Loader hides the whole document to prevent a "Flash of unhyphenated content" (FOUHC) until hyphenation has finished. If `focus()` is called while the document is hidden, the focus will not change.

To prevent that behaviour experiment with [different settings for hiding](https://mnater.github.io/Hyphenopoly/Setup.html#hide). Using `"element"` or `"text"` worked in my tests.

Note: Setting `focus()` in a [hyphenopolyEnd-Event](https://mnater.github.io/Hyphenopoly/Events.html#hyphenopolyend-event) will not work, because the default action (unhiding) happens after the user defined actions. I'll have to think about a new event that triggers, when the document is available for other scripts.

**Comment by Bertijn** [comment]
Hi @mnater ,

Thanks for getting back to me! The hide: "text" does indeed seem to fix the focus issue! We'll do some further tests, but I'm hopeful.

Yet again, thanks for the explanation and solution! Take care!
