### ISSUE TITLE
Question: Change exceptions after loading Hyphenopoly_Loader.js

### ISSUE THREAD

**Issue by AndreasFerdinand** [mnater/Hyphenopoly#97]
Hi,

is it possible to change the configuration expecially the exceptions after the file Hyphenopoly_Loader.js is loaded? 
I use Hyphenopoly.hyphenators for Strings (https://github.com/mnater/Hyphenopoly/blob/master/docs/Hyphenators.md#use-hyphenopolyhyphenators-for-strings) and I need to change the exceptions as described below:

```HTML
<script src="./Hyphenopoly_Loader.js"></script>
<script>
    Hyphenopoly.hyphenators["en-us"].then((hyphenator_en) => {
        /// ******** NEED TO CHANGE EXCEPTIONS HERE *******
        console.log(hyphenator_en("Hyphenation")); //Hy•phen•ation
        console.log(hyphenator_en("Hyphenation", ".hyphenatePipe")); //Hy|phen|ation
    })
</script>
```

Thank you and regards
Andi

**Comment by mnater** [comment]
Hi

It's not possible with the current API because Hyphenopoly preprocesses the exceptions provided in setup.

Theoretically it would be possible to change the excpetions directly in the Hyphenopoly-object:
````html
<script src="./Hyphenopoly_Loader.js"></script>
<script>
    Hyphenopoly.hyphenators["en-us"].then((hyphenator_en) => {
        /// ******** NEED TO CHANGE EXCEPTIONS HERE *******
        Hyphenopoly.languages.get("en-us").exc.set("Hyphenation", "Hyphen-ation");
        console.log(hyphenator_en("Hyphenation")); //Hy•phen•ation
        console.log(hyphenator_en("Hyphenation", ".hyphenatePipe")); //Hy|phen|ation
    })
</script>
````

But since this it not "official" API it might break in the future.

Before we think about implementing a new feature: why can you change the exceptions only at a later date? It would help me if I could understand this clearly.

Kind regards,
Mathias

**Comment by AndreasFerdinand** [comment]
I'm working on a project to support the ground school of my son. The target is to convert a text, so that each syllable of a word is displayed in an other color (this is already working). e.g.:

Hy•phen•ation ==>
```HTML
<font class="blue">Hy</font>
<font class="red">phen</font>
<font class="blue">ation</font>
```

But now I want to use a textarea as input field for the source text, an additional text input field for the exceptions and a button to start the conversion. 

After the button is hit, the exceptions and the source text shold be read and than transfomed into the red-blue text, which sould then be displayed somwhere on the page. If a word is not converted correct, the user shoud be able to add an excetion to the text field and start the conversion again.

Thank you
Andi

**Comment by mnater** [comment]
So teachers can then make text more readable for the children, right?

Given the fact that you include the ability to correct false separations, you probably know that Hyphenopoly is not necessarily suitable for your use case (Hyphenopoly does not find all separation points: https://mnater.github.io/Hyphenopoly/Coping-with-hyphenation-errors.html).

Let's put that aside.

I see three possible approaches to the problem.

1) We look for a way to solve the problem with the current version (e.g. as described above) or by resetting Hyphenopoly each time and then regenerating the configuration (and the exceptions).

2) You implement your own exception handling: First apply the exceptions and then separate the rest by Hyphenopoly. (Hyphenopoly does not further separate words that are already separated).

3) I implement the ability to change the configuration at a later time.

Let's compare the three possibilities:
1) This will be messy and I am not sure it will work in the long run.

2) Here you have the work, but since you are using Hyphenopoly outside the typical use cases, I think it is reasonable.

3) That would take some time, because I don't have much time at the moment. And it would make Hyphenopoly several bytes bigger, which I don't necessarily strive for, unless it offers a corresponding added value.

I would suggest option 2). What do you think? Do you see other options? Or are there more arguments for option 3)?

Best regards,
Mathias

**Comment by AndreasFerdinand** [comment]
I think option 2 is applicable for my scenario. It is not necessary that you change you implementation. Thank you
Andi
